############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Posts"
url = "blog/"
weight = 3

[[main]]
name = "Categories"
url = "categories/"
weight = 4

[[main]]
name = "Team"
url = "authors/"
weight = 5

[[main]]
name = "Contact"
url = "contact/"
weight = 6

[[main]]
weight = 7
name = "Examples"
hasChildren = true

[[main]]
parent = "Examples"
name = "Elements"
url = "elements/"

[[main]]
parent = "Examples"
name = "404 Page"
url = "404/"


# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 2
