name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Environment variables available to all jobs and steps in this workflow
env:
  HUGO_ENV: production

jobs:
  # Build job
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Cache Node Modules
      - name: Cache Node Modules
        id: CacheStep
        uses: pat-s/always-upload-cache@v3.0.11
        env:
          cache-name: cache-node_modules-${{ runner.os }}
        with:
          path: ${{github.workspace}}/node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Setup Project
        shell: sh
        run: npm run project-setup

      - name: Install npm dependencies
        shell: sh
        run: npm install

      - name: Build Website
        shell: sh
        run: npm run build

      - name: Copy Output to Website Root
        shell: sh
        run: rsync -avhW public ~/Projects/CrescentWebStorage/public/
