name: Deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Environment variables available to all jobs and steps in this workflow
env:
  HUGO_ENV: production

jobs:
  # Build job
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Project
        run: npm run project-setup

      - name: Install npm dependencies
        run: npm install

      - name: Publish to GitHub Pages
        run: npm run build
